# -*- mode: python ; coding: utf-8 -*-
"""WIF Bunker PyInstaller spec — single-directory build."""

import os
from PyInstaller.utils.hooks import copy_metadata

block_cipher = None

# ── Hidden imports ──
# These are NOT imported by wif_bunker — they're loaded internally by
# google-auth's _default.py at runtime based on credential type. PyInstaller
# can't trace them because they're string-based dynamic imports inside
# google-auth, not our code.
hiddenimports = [
    # google-auth credential types (loaded dynamically by _default.py)
    'google.auth.identity_pool',
    'google.auth.external_account',
    'google.auth.impersonated_credentials',
    'google.auth._default',
    # cryptography backends (loaded via entry points)
    'cryptography.hazmat.backends.openssl',
    'cryptography.hazmat.backends.openssl.backend',
    'cryptography.hazmat.bindings.openssl.binding',
    # YubiKey PIV support (lazy imports — PyInstaller traces
    # ykman/yubikit/smartcard transitively from these entry points)
    'wif_bunker.keystore.yubikey',
    'wif_bunker.attestation.yubikey',
]

# ── Package metadata ──
# google-auth and requests check their own distribution metadata at runtime.
# Without this, you get "pkg_resources.DistributionNotFound" errors.
datas = []
for pkg in ('google-auth', 'requests', 'cryptography', 'certifi', 'urllib3', 'charset-normalizer'):
    try:
        datas += copy_metadata(pkg, recursive=True)
    except Exception:
        pass  # Package may not be installed in dev

# ── Attestation root certificates ──
# TPM EK root/intermediate CAs used by --attest to verify the EK cert chain.
# These are data files that PyInstaller won't find automatically.
datas += [
    ('wif_bunker/attestation/roots/roots/*.pem', 'wif_bunker/attestation/roots/roots'),
    ('wif_bunker/attestation/roots/intermediates/*.pem', 'wif_bunker/attestation/roots/intermediates'),
    ('wif_bunker/attestation/roots/manually-managed/*.pem', 'wif_bunker/attestation/roots/manually-managed'),
    ('wif_bunker/attestation/roots/yubico/*.pem', 'wif_bunker/attestation/roots/yubico'),
]

# ── Excludes ──
# Trim unused packages to reduce binary size.
excludes = [
    'tkinter',
    'unittest',
    'xmlrpc',
    'pydoc',
    'doctest',
    'test',
]

# ── hardmTLS native library ──
# Built by `cargo build --release` in hardmtls-native/ before PyInstaller runs.
# Bundled into dist/wif-bunker/hardmtls/ so certificate_config.json can point
# libs.ecp_client and libs.tls_offload at it.
import platform

_hardmtls_dir = os.path.join('hardmtls-native', 'target', 'release')
if platform.system() == 'Darwin':
    _hardmtls_lib = os.path.join(_hardmtls_dir, 'libhardmtls.dylib')
elif platform.system() == 'Linux':
    _hardmtls_lib = os.path.join(_hardmtls_dir, 'libhardmtls.so')
else:
    _hardmtls_lib = os.path.join(_hardmtls_dir, 'hardmtls.dll')

hardmtls_binaries = [(_hardmtls_lib, 'hardmtls')] if os.path.exists(_hardmtls_lib) else []

a = Analysis(
    ['wif_bunker/cli.py'],
    pathex=[],
    binaries=hardmtls_binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# Windows version info — generated by release workflow from version_info.txt.in
version_file = 'version_info.txt' if os.path.exists('version_info.txt') else None

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='wif-bunker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version=version_file,
    contents_directory='lib',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='wif-bunker',
)
